#https://alacritty.org/config-alacritty.html#s62
[general]
live_config_reload = true
working_directory = "None"

# Themes --
import = [
  "~/.config/alacritty/nordic.toml",
  "~/.config/alacritty/keybinds.toml",
]

[font]
# normal = { family = "MesloLGM Nerd Font Mono", style = "Regular" }
# bold = { family = "MesloLGM Nerd Font Mono", style = "Bold" }
# italic = { family = "MesloLGM Nerd Font Mono", style = "Italic" }
# old
normal = { family = "JetbrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetbrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetbrainsMono Nerd Font", style = "Italic" }
size = 17.0

[scrolling]
history = 10000

[window]
title = "Alacritty"
decorations = "none"
blur = false
opacity = 1
padding.x = 10
padding.y = 10

[window.dimensions]
columns = 160
lines = 80

[cursor]
style.shape = "Beam"
style.blinking = "On"
vi_mode_style.shape = "Block"
vi_mode_style.blinking = "On"

[colors]
transparent_background_colors = false
draw_bold_text_with_bright_colors = true
